courses_cour:
    resource: "@CoursesBundle/Resources/config/routing/course.yml"
    prefix:   /courses

courses_homepage:
    path:     /
    # pattern:  /hello/{name}
    defaults: { _controller: CoursesBundle:Course:index }

category_categ:
    # ..path:     /categ
    resource: "@CoursesBundle/Resources/config/routing/category.yml"
    prefix:   /category/{slug}/{page}
    # pattern:  /category/{slug}
    # defaults: { _controller: CoursesBundle:Category:show }
#src/bun/res/conf/routing.yml
# CoursesBundle_course:
#      resource: "@CoursesBundle/Resources/config/routing/course.yml"
#     prefix: /courses

# CoursesBundle_homepage:
#     pattern: /
#     defaults: { _controller: CoursesBundle:Course:index }