CoursesBundleEntityCourse:
    properties:
        name:
            - NotBlank: ~
            # - Email: ~
        contents:
            - NotBlank: ~
        price:
            - NotBlank: ~
        created_at:
            - NotBlank: ~
        updated_at:
            - NotBlank: ~    
        token:
            - NotBlank: ~
        # url:
        #     - Url: ~
        file:
            - Image: ~ #here we are
        type:
            - NotBlank: ~
            - Choice: { callback: getTypeValues }