CoursesBundleEntityCourse:
    properties:
        name:
            - NotBlank: ~
            # - Email: ~
        contents:
            - NotBlank: ~
        price:
            - NotBlank: ~
        created_at:
            - NotBlank: ~
        # url:
        #     - Url: ~