course_index:
    path:     /
    defaults: { _controller: "CoursesBundle:Course:index" }
    methods:  GET

course_show:
    path:     /{name}/{price}/{id}/{category}
    defaults: { _controller: "CoursesBundle:Course:show" }
    methods:  GET

course_new:
    path:     /new
    defaults: { _controller: "CoursesBundle:Course:new" }
    # methods:  [GET, POST]

course_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoursesBundle:Course:edit" }
    # methods:  [GET, POST]

course_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoursesBundle:Course:delete" }
    methods:  DELETE
